# Generated by Django 3.2.16 on 2024-03-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240302_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
